### ISSUE TITLE
Add link to "Quick Install Guide" after flashing

### ISSUE THREAD

**Issue by elibosley** [unraid/usb-creator-next#23]
Add a link to https://docs.unraid.net/unraid-os/getting-started/quick-install-guide/ 

After flashing is completed

Button should say: Quick Setup Guide

**Comment by ljm42** [comment]
Please use this "go link" instead: https://docs.unraid.net/go/quick-install-guide

This go link is stable and should continue to work as the docs are reorganized.

Along these lines, please ensure all URLs in the repo that directly link to `https://docs.unraid.net/unraid-os/getting-started/quick-install-guide/` are changed to `https://docs.unraid.net/go/quick-install-guide`:
https://github.com/search?q=repo:unraid/usb-creator-next%20repo:unraid/usb-creator-next%20docs.unraid.net&type=code
