### ISSUE TITLE
[BUG]: Unraid 7.0.0 beta2 not available for flashing

### ISSUE THREAD

**Issue by asychev** [unraid/usb-creator-next#49]
### What happened?

![image](https://github.com/user-attachments/assets/93737b77-3815-4e32-a595-44a2cd6550ea)
![image](https://github.com/user-attachments/assets/13f8236c-8e11-436e-afa4-457f450f745e)

`Next` button is not active when selecting `Unraid Os Releases (Next Branch)`
Was working week or two ago

### Version

1.8.5 (Default)

### What host operating system were you using?

Windows

### Host OS Version

23H2

### Selected OS

Unraid 7.0.0-beta2

### Which Raspberry Pi Device are you using?

Raspberry Pi 5

### What kind of storage device are you using?

USB Pen Drive

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

**Comment by ljm42** [comment]
There may have been an issue with caching the JSON, the beta download options were available after uninstall/reinstalling the USB Creator
