### ISSUE TITLE
[FEATURE]: Add a .RPM for fedora and other distros and add .pacman for arch

### ISSUE THREAD

**Issue by ryzendew** [unraid/usb-creator-next#52]
### Is your feature request related to a problem? Please describe.

No issue

### Describe the solution you would like to see implemented

supporting linux is not just saying here is a .deb and that covers everything since times have changed and it's the least used distro now and support should always be given to the big 3.

### Describe alternatives you've considered

proxmox

### Additional context

just want what's right for linux

### Version

1.8.5 (Default)

**Comment by elibosley** [comment]
Thank you for this suggestion, we've got this on our roadmap already #34 so I'm closing this out as a duplicate for now.
